name: Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git crypt Unlock
        uses: zemuldo/git-crypt-unlock@v2.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_GRIP: ${{ secrets.GPG_KEY_GRIP }}
          GPG_KEY_PASS: ${{ secrets.GPG_KEY_PASS }}


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm i --frozen-lockfile

      - name: Build frontend
        run: pnpm build

      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v3
        with:
          pages_threshold: major_outage

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist
          fqdn: wenjuan.ygqygq2.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
